edition = "2021"
max_width = 512
hard_tabs = false
tab_spaces = 4

use_small_heuristics = "Max"
fn_call_width = 60
struct_lit_width = 18
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50

reorder_imports = true
